node {
 def mvnHome
 stage('Preparation') { // for display purposes
  // Get some code from a GitHub repository
   git 'https://github.com/kimpetertanui/Magic.git'
  // Get the Maven tool.
  // ** NOTE: This 'M3' Maven tool must be configured
  // **       in the global configuration.
   mvnHome = tool 'Maven'
 }
 stage('Build') {
  // Run maven build
  if (isUnix()) {
     sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
  } else {
     bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
  }
}
stage('Test')   {
   //Perform test
   echo 'Execute the script'
    if (isUnix()) {
      sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore test"
  } else {
     bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore test/)
  }

 }
 stage('Results') {
  junit '**/target/surefire-reports/TEST-*.xml'
  archive 'target/*.jar'
}
}